const ApiError = require("../../exceptions/api.error");

class AuthController {
    async check(req, res, next) {
        try {

        }
        catch (e) {
            next(e)
        }
    }

    async login(req, res, next) {
        try {

        }
        catch (e) {
            next(e)
        }
    }

    async register(req, res, next) {
        try {

        }
        catch (e) {
            next(e)
        }
    }
}

module.exports = new AuthController()